version: '3'
services:
  maplestory:
    build:
      context: ../../
      dockerfile: ./gms-server/docker/Dockerfile
    depends_on:
      - db
    ports:
      # Web
      - "8686:8686"
      # Login server
      - "8484:8484"
      # Channels.
      - "7575-7577:7575-7577"
    volumes:
      - ./gms-server/scripts:/opt/server/scripts
      - ./gms-server/scripts-zh-CN:/opt/server/scripts-zh-CN
      - ./gms-server/wz:/opt/server/wz
      - ./gms-server/wz-zh-CN:/opt/server/wz-zh-CN
      - ./gms-server/docker/application.yml:/opt/server/application.yml

  db:
    image: mysql:8.4.0
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - ./gms-server/docker/docker-db-data:/var/lib/mysql
