version: '3'
services:
  maplestory:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    network_mode: "host"
    depends_on:
      - db
    ports:
      - "8686:8686"
      # Login server
      - "8484:8484"
      # Channels.
      # Format: WWCC, where WW is 75 plus the world number and CC is 75 plus the channel number (both zero indexed).
      # In this case, world 1 channels 1-3.
      - "7575-7577:7575-7577"
    volumes:
      # Config changes can be reloaded without rebuilding the image.
      # Still requires a redeployment as they're sourced on startup.
      - ../scripts:/opt/server/scripts
      - ../scripts-zh-CN:/opt/server/scripts-zh-CN
      - ../wz:/opt/server/wz
      - ../wz-zh-CN:/opt/server/wz-zh-CN

  db:
    image: mysql:8.4.0
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
